name = "main"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = "== 0.53.0"
gleam_yielder = "== 1.1.0"
stdin = { path = "../../stdin" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
